In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)

In [3]:
df = pd.read_csv('gurgaon_properties.csv')

In [4]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sohna,flat,signature global park,0.70,6071.0,1153.022566,Carpet area: 1153 (107.12 sq.m.),3,3,3,pooja room,"001, Sohna, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,breez global hill view,0.32,5776.0,554.016620,Carpet area: 554 (51.47 sq.m.),2,2,2,not available,"1905, Sohna, Gurgaon, Haryana",19.0,North,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Sohna is a peripheral area on the southern sid...,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 Bedroom House for sale in Baldev Nagar,house,independent,0.45,5000.0,900.000000,Carpet area: 900 (83.61 sq.m.),3,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 Bedroom House for sale in Palam Vihar,house,ansals palam vihar,2.75,17662.0,1557.000000,Plot area 173(144.65 sq.m.),3,3,3,"pooja room,study room","Palam Vihar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","For sell 173 sq- Yard plot area , complete woo...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Ligh...","['Private Garden / Terrace', 'Maintenance Staff']","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,5 Bedroom House for sale in Gandhi Nagar,house,independent,0.45,90000.0,50.000000,Built Up area: 50 (4.65 sq.m.),5,3,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [6]:
df.shape

(3961, 20)

In [7]:
df.duplicated().sum()

0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3961 entries, 0 to 3960
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3961 non-null   object
 1   property_type    3961 non-null   object
 2   society          3960 non-null   object
 3   price            3941 non-null   float64
 4   price_per_sqft   3941 non-null   float64
 5   area             3941 non-null   float64
 6   areaWithType     3961 non-null   object
 7   bedRoom          3961 non-null   int64
 8   bathroom         3961 non-null   int64
 9   balcony          3961 non-null   object
 10  additionalRoom   3961 non-null   object
 11  address          3950 non-null   object
 12  floorNum         3940 non-null   float64
 13  facing           2784 non-null   object
 14  agePossession    3960 non-null   object
 15  nearbyLocations  3754 non-null   object
 16  description      3961 non-null   object
 17  furnishDetails   2929 non-null   object
 18  features         3252 non-null   object
 19  rating           3511 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 619.0+ KB

In [9]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                20
price_per_sqft       20
area                 20
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             21
facing             1177
agePossession         1
nearbyLocations     207
description           0
furnishDetails     1032
features            709
rating              450
dtype: int64

In [10]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sohna,flat,signature global park,0.70,6071.0,1153.022566,Carpet area: 1153 (107.12 sq.m.),3,3,3,pooja room,"001, Sohna, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,breez global hill view,0.32,5776.0,554.016620,Carpet area: 554 (51.47 sq.m.),2,2,2,not available,"1905, Sohna, Gurgaon, Haryana",19.0,North,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Sohna is a peripheral area on the southern sid...,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 Bedroom House for sale in Baldev Nagar,house,independent,0.45,5000.0,900.000000,Carpet area: 900 (83.61 sq.m.),3,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 Bedroom House for sale in Palam Vihar,house,ansals palam vihar,2.75,17662.0,1557.000000,Plot area 173(144.65 sq.m.),3,3,3,"pooja room,study room","Palam Vihar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","For sell 173 sq- Yard plot area , complete woo...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Ligh...","['Private Garden / Terrace', 'Maintenance Staff']","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,5 Bedroom House for sale in Gandhi Nagar,house,independent,0.45,90000.0,50.000000,Built Up area: 50 (4.65 sq.m.),5,3,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [11]:
sector = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip()

In [12]:
df.insert(loc=3, column='sector', value=sector)

In [13]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sohna,flat,signature global park,Sohna,0.70,6071.0,1153.022566,Carpet area: 1153 (107.12 sq.m.),3,3,3,pooja room,"001, Sohna, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,breez global hill view,Sohna,0.32,5776.0,554.016620,Carpet area: 554 (51.47 sq.m.),2,2,2,not available,"1905, Sohna, Gurgaon, Haryana",19.0,North,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Sohna is a peripheral area on the southern sid...,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 Bedroom House for sale in Baldev Nagar,house,independent,Baldev Nagar,0.45,5000.0,900.000000,Carpet area: 900 (83.61 sq.m.),3,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 Bedroom House for sale in Palam Vihar,house,ansals palam vihar,Palam Vihar,2.75,17662.0,1557.000000,Plot area 173(144.65 sq.m.),3,3,3,"pooja room,study room","Palam Vihar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","For sell 173 sq- Yard plot area , complete woo...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Ligh...","['Private Garden / Terrace', 'Maintenance Staff']","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,5 Bedroom House for sale in Gandhi Nagar,house,independent,Gandhi Nagar,0.45,90000.0,50.000000,Built Up area: 50 (4.65 sq.m.),5,3,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [14]:
df['sector'] = df['sector'].str.lower().str.strip()

In [15]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sohna,flat,signature global park,sohna,0.70,6071.0,1153.022566,Carpet area: 1153 (107.12 sq.m.),3,3,3,pooja room,"001, Sohna, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,breez global hill view,sohna,0.32,5776.0,554.016620,Carpet area: 554 (51.47 sq.m.),2,2,2,not available,"1905, Sohna, Gurgaon, Haryana",19.0,North,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Sohna is a peripheral area on the southern sid...,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 Bedroom House for sale in Baldev Nagar,house,independent,baldev nagar,0.45,5000.0,900.000000,Carpet area: 900 (83.61 sq.m.),3,2,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 Bedroom House for sale in Palam Vihar,house,ansals palam vihar,palam vihar,2.75,17662.0,1557.000000,Plot area 173(144.65 sq.m.),3,3,3,"pooja room,study room","Palam Vihar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","For sell 173 sq- Yard plot area , complete woo...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Ligh...","['Private Garden / Terrace', 'Maintenance Staff']","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,5 Bedroom House for sale in Gandhi Nagar,house,independent,gandhi nagar,0.45,90000.0,50.000000,Built Up area: 50 (4.65 sq.m.),5,3,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [16]:
df['sector'].value_counts()

sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 37d                                                    68
sector 86                                                     67
sector 104                                                    66
sector 107                                                    60
sector 108                                                    59
sector 95                                                     57
sector 56                                                     57
sector 48                                                     56
sector 89                                                     56
sector 70a                                                    54
sector 37c                                                    53
sector 70                                                     53
nirvana country                                               53
sector-33 sohna                                               51
sector 84                                                     51
palam vihar                                                   50
sector 67                                                     48
sector 66                                                     46
sector 103                                                    45
dlf phase 2                                                   43
sector 113                                                    43
dlf phase 1                                                   43
sector 61                                                     42
sector 82                                                     42
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 72                                                     29
sector 77                                                     29
sector 54                                                     27
laxman vihar                                                  27
sector 71                                                     27
dlf phase 4                                                   26
sector 112                                                    24
sector 88a                                                    23
sector 33                                                     23
sector 111                                                    22
dlf phase 3                                                   22
sector 67a                                                    22
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     17
sector 62                                                     17
sector 110                                                    16
sector 99                                                     16
sushant lok phase 3                                           16
sector 14                                                     15
sector 60                                                     15
sector 63                                                     15
sector 76                                                     14
dlf phase 5                                                   14
sector 3                                                      14
sector 1 imt manesar                                          14
sector 53                                                     14
gwal pahari                                                   14
rajendra park                                                 14
sector 52                                                     14
sector 46                                                     13
sector 36a                                                    13
laxman vihar phase 2                                          13
uppals southend                                               12
sohna road                                                    12
sector 38                                                     12
sector 31                                                     12
sector 39                                                     12
sector 93                                                     12
sector 50                                                     12
ashok vihar phase 3 extension                                 11
sector 47                                                     11
sector 9a                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 4                                                       9
sector 55                                                      9
sector 95a                                                     9
ashok vihar phase 2                                            9
south city 1                                                   9
palam vihar extension                                          8
sector 43                                                      8
sector 10a                                                     8
malibu town                                                    8
sector 57                                                      8
sector 59                                                      8
mehrauli  road                                                 8
dwarka expressway                                              8
sector 89 a                                                    8
c block sushant lok phase 1                                    8
sector 40                                                      8
surat nagar 1                                                  7
sector 51                                                      7
sector 11                                                      7
mianwali colony                                                7
sector 36 sohna                                                7
sector 26                                                      7
new colony                                                     7
sector 58                                                      7
sector 1                                                       6
jyoti park                                                     6
jacobpura                                                      6
sector 5                                                       6
rajiv nagar                                                    6
ashok vihar                                                    6
sector 30                                                      5
saraswati vihar                                                5
sector 2                                                       5
ansal plaza                                                    5
arjun nagar                                                    5
sector 23a                                                     5
sector 28                                                      5
sushant lok phase 2                                            5
dayanand colony                                                5
sector 80                                                      5
manesar                                                        5
chakkarpur                                                     5
greenwood city                                                 5
sector 105                                                     5
subhash nagar                                                  5
sector 9                                                       5
new palam vihar                                                5
sector 17                                                      4
dharam colony                                                  4
krishna colony                                                 4
new                                                            4
sector 36                                                      4
suncity                                                        4
garhi harsaru                                                  4
madanpuri                                                      4
surya vihar                                                    4
sector 3a                                                      4
shivpuri                                                       4
sector 45                                                      4
shivaji nagar                                                  4
baldev nagar                                                   4
imt manesar                                                    4
ravi nagar                                                     4
sector 12                                                      4
sector 6                                                       4
sector 12a                                                     4
bhondsi                                                        4
adarsh nagar                                                   4
bhim nagar                                                     4
vishnu garden                                                  4
devilal colony                                                 4
valley view estate                                             4
gandhi nagar                                                   3
mg road                                                        3
sector 17b                                                     3
shakti nagar                                                   3
sector 23                                                      3
maruti kunj                                                    3
laxmi garden                                                   3
sector 15                                                      3
b block sushant lok phase 1                                    3
sector 73                                                      3
sector 88b                                                     3
sector 110 a                                                   3
sector 17a                                                     3
sector 8                                                       3
a block sushant lok phase 1                                    3
prem nagar                                                     3
sector 27                                                      3
patel nagar                                                    3
mohan nagar                                                    2
pratap nagar                                                   2
golf course road                                               2
sector 21                                                      2
, delhi ncr                                                    2
rajiv chowk                                                    2
nars                                                           2
block a surya vihar                                            2
sheetla colony                                                 2
rosewood                                                       2
ambience island                                                2
sohna  road                                                    2
sector 41                                                      2
new palam vihar phase 2                                        2
manohar nagar                                                  2
sector 15 part 1                                               2
bissar                                                         2
bhawani enclave                                                2
sector 15 part 2                                               2
sispal vihar                                                   2
surat nagar                                                    2
sector 32                                                      2
shankar vihar                                                  2
mayfield garden                                                2
faridabad road                                                 2
golf course ext road                                           2
samaspur                                                       2
sushant lok                                                    2
acharya puri                                                   2
west rajiv nagar                                               2
daulatabad                                                     2
sector 24                                                      2
shanti nagar                                                   2
new palam vihar phase 1                                        2
sector-2 sohna                                                 2
farukhnagar                                                    2
hira nagar                                                     2
lajpat nagar                                                   2
iffco chowk                                                    2
sector-11 sohna                                                2
surat nagar phase 2                                            2
new basti                                                      2
udyog vihar phase 1                                            1
bptp                                                           1
dhankot                                                        1
hsiidc plot sector 1 imt manesar                               1
v block dlf phase 3                                            1
nirvana country pocket h                                       1
sector-7 hous                                                  1
ashok vihar phase 3                                            1
gopal nagar, garhi ghasita, sonipat                            1
near pataudi chowk                                             1
naharpur rupa                                                  1
damdma                                                         1
khandsa                                                        1
sector 42                                                      1
part 3 sector 5                                                1
ashok vihar phase i                                            1
block g sector-57                                              1
laxmna vihar, phase 2                                          1
sector 4 urban estate                                          1
mahalaxmi garden, rajendra place                               1
ansal's palam vihar                                            1
ats marigold                                                   1
urban estate, sector 5                                         1
south city                                                     1
civil l                                                        1
rajiv colony                                                   1
sector 37b                                                     1
sector 9b                                                      1
near euro                                                      1
bhora kalan                                                    1
sector-5 sheetla colony                                        1
heritage city                                                  1
alipur                                                         1
sector-5 sohna                                                 1
sec 3 bhim vihar part 1 bhimgher kheri                         1
near nand hospital                                             1
tekchand nagar                                                 1
hno 13 sagar enclave sura                                      1
saroop garden rajendra park                                    1
near sector 1 market                                           1
ram nagar                                                      1
sector 37a                                                     1
sector 21a faridabad                                           1
sector 5 chowk                                                 1
sector-35 sohna                                                1
sadar bazar                                                    1
park view                                                      1
new jyoti park                                                 1
mahavir pura                                                   1
cyber city                                                     1
jacobpura near sadar bazar                                     1
lucknow                                                        1
kanahi                                                         1
b1 block sector 57                                             1
garauli kalan                                                  1
rattan garden                                                  1
new colony, sector 7                                           1
huda saraswati vihar                                           1
shivji park colony                                             1
sai kunj                                                       1
anand garden, sector-105                                       1
sector 13                                                      1
carterpuri village                                             1
near khandsa road                                              1
g block dlf city phase 1                                       1
bhimgarh kheri phase 3                                         1
devi lal colony gali no 12 gurgaon nr omkar public school      1
old delhi road, opp sector-14                                  1
jat colony,fazilpur/taj nagar road                             1
om nagar                                                       1
pataudi road                                                   1
sultanpur                                                      1
laxman vihar, railway road,                                    1
vir nagar                                                      1
ravi nager basai road                                          1
saraswati enclave                                              1
begampur khatola                                               1
kheri                                                          1
godrej aria , sector 79 ,                                      1
sector 17c                                                     1
block h ashok vihar phase iii extension                        1
Name: sector, dtype: int64

In [30]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [31]:
df['sector'] = df['sector'].str.replace('sector 3 phase 3 extension','sector 3')
df['sector'] = df['sector'].str.replace('sector 3 phase 2','sector 3')

In [42]:
df['sector'].value_counts()

sohna road road      175
sector 102           113
sector 85            110
sector 92            105
sector 69             94
sector 90             91
sector 65             90
sector 81             90
sector 109            88
sector 79             80
sector 33             74
sector 104            73
sector 83             69
sector 37d            68
sector 43             67
sector 86             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 37c            53
sector 84             51
sector 26             50
sector 4              49
sector 49             48
sector 67             48
sector 28             47
sector 66             46
sector 103            45
sector 3              44
sector 25             43
sector 113            43
sector 82             42
sector 61             42
sector 7              39
sector 106            38
sector 12             37
manesar               33
sector 99a            32
sector 54             31
sector 68             30
sector 72             29
sector 77             29
sector 71             27
sector 112            24
sector 110            24
sector 24             24
sector 57             24
sector 14             23
sector 105            23
sector 88a            23
sector 67a            22
sector 111            22
sector 11             21
sector 82a            20
sector 22             20
sector 78             19
sector 47             19
sector 63a            18
sector 74             18
gwal pahari           18
sector 91             17
sector 62             17
sector 99             16
sector 76             15
sector 63             15
sector 60             15
sector 53             14
sector 55             14
sector 52             14
sector 6              13
sector 46             13
sector 23             13
sector 9              13
sector 36a            13
sector 39             12
sector 93             12
sector 31             12
sector 38             12
sector 9a             11
sector 36             11
sector 41             11
sector 13             10
sector 45              9
sector 8               8
sector 40              8
dwarka expressway      8
sector 10a             8
sector 17              8
sector 59              8
sector 58              7
sector 51              7
sector 5               6
sector 21              6
sector 1               6
sector 15              6
sector 30              5
sector 80              5
sector 27              3
sector 17b             3
sector 73              3
sector 88b             3
sector 17a             3
Name: sector, dtype: int64

In [33]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [34]:
df.loc[831,'sector'] = 'sector 37'
df.loc[1586,'sector'] = 'sector 92'
df.loc[882,'sector'] = 'sector 90'
df.loc[3238,'sector'] = 'sector 76'

In [35]:
df[df['sector'] == 'new']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [36]:
df[df['sector'] == 'new sector 2']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [37]:
df.loc[[305,1132,1936,2382,2557],'sector'] = 'sector 110'

In [38]:
df[df['sector'] == 'new sector 2']

Empty DataFrame
Columns: [property_name, property_type, society, sector, price, price_per_sqft, area, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [39]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [40]:
df['sector'].value_counts()

sohna road road      175
sector 102           113
sector 85            110
sector 92            105
sector 69             94
sector 90             91
sector 65             90
sector 81             90
sector 109            88
sector 79             80
sector 33             74
sector 104            73
sector 83             69
sector 37d            68
sector 43             67
sector 86             67
sector 95             66
sector 50             65
sector 89             64
sector 2              63
sector 107            60
sector 108            59
sector 56             57
sector 48             56
sector 70a            54
sector 70             53
sector 37c            53
sector 84             51
sector 26             50
sector 4              49
sector 49             48
sector 67             48
sector 28             47
sector 66             46
sector 103            45
sector 3              44
sector 25             43
sector 113            43
sector 82             42
sector 61             42
sector 7              39
sector 106            38
sector 12             37
manesar               33
sector 99a            32
sector 54             31
sector 68             30
sector 72             29
sector 77             29
sector 71             27
sector 112            24
sector 110            24
sector 24             24
sector 57             24
sector 14             23
sector 105            23
sector 88a            23
sector 67a            22
sector 111            22
sector 11             21
sector 82a            20
sector 22             20
sector 78             19
sector 47             19
sector 63a            18
sector 74             18
gwal pahari           18
sector 91             17
sector 62             17
sector 99             16
sector 76             15
sector 63             15
sector 60             15
sector 53             14
sector 55             14
sector 52             14
sector 6              13
sector 46             13
sector 23             13
sector 9              13
sector 36a            13
sector 39             12
sector 93             12
sector 31             12
sector 38             12
sector 9a             11
sector 36             11
sector 41             11
sector 13             10
sector 45              9
sector 8               8
sector 40              8
dwarka expressway      8
sector 10a             8
sector 17              8
sector 59              8
sector 58              7
sector 51              7
sector 5               6
sector 21              6
sector 1               6
sector 15              6
sector 30              5
sector 80              5
sector 27              3
sector 17b             3
sector 73              3
sector 88b             3
sector 17a             3
Name: sector, dtype: int64

In [41]:
df.shape

(3802, 21)

In [43]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sohna,flat,signature global park,sohna road road,0.70,6071.0,1153.022566,Carpet area: 1153 (107.12 sq.m.),3.0,3.0,3,pooja room,"001, Sohna, Gurgaon, Haryana",2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction5 out of..."
1,2 BHK Flat in Sohna,flat,breez global hill view,sohna road road,0.32,5776.0,554.016620,Carpet area: 554 (51.47 sq.m.),2.0,2.0,2,not available,"1905, Sohna, Gurgaon, Haryana",19.0,North,1 to 5 Year Old,"['Huda City Centre', 'Omaxe City Centre', 'Nin...",Sohna is a peripheral area on the southern sid...,"['2 Wardrobe', '2 Bed', '1 Water Purifier', '4...","['Power Back-up', 'Lift(s)', 'Maintenance Staf...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,3 Bedroom House for sale in Baldev Nagar,house,independent,sector 7,0.45,5000.0,900.000000,Carpet area: 900 (83.61 sq.m.),3.0,2.0,0,not available,"Baldev Nagar, Sector 9, Baldev Nagar, Gurgaon,...",1.0,NaN,undefined,"['Ankur Clinic and Maternity Home', 'Navjeevan...",Villa is available for sale. It carpet area of...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3,3 Bedroom House for sale in Palam Vihar,house,ansals palam vihar,sector 2,2.75,17662.0,1557.000000,Plot area 173(144.65 sq.m.),3.0,3.0,3,"pooja room,study room","Palam Vihar, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","For sell 173 sq- Yard plot area , complete woo...","['5 Fan', '1 Exhaust Fan', '5 Geyser', '1 Ligh...","['Private Garden / Terrace', 'Maintenance Staff']","['Environment5 out of 5', 'Lifestyle5 out of 5..."
4,5 Bedroom House for sale in Gandhi Nagar,house,independent,sector 28,0.45,90000.0,50.000000,Built Up area: 50 (4.65 sq.m.),5.0,3.0,0,not available,"Gandhi Nagar, Sector 11, Gandhi Nagar, Gurgaon...",1.0,NaN,undefined,NaN,Best in class property available at gandhi nag...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [44]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [45]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
554,flat,ss the leaf,sector 85,1.18,10094.0,1169.011294,Super Built up area 1671(155.24 sq.m.)Built Up...,2.0,3.0,3,pooja room,12.0,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...","['2 Wardrobe', '3 Fan', '1 Exhaust Fan', '11 L...","['Centrally Air Conditioned', 'Water purifier'..."
525,house,independent,sector 2,2.95,15989.0,1845.000000,Plot area 205(171.41 sq.m.),4.0,4.0,3+,not available,2.0,North-West,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '10 L...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."
344,flat,gls arawali homes,sohna road road,0.35,6076.0,576.036866,Super Built up area 576(53.51 sq.m.),2.0,2.0,2,not available,12.0,NaN,0 to 1 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian..."
367,flat,signature global grand iva,sector 103,0.50,6667.0,749.962502,Built Up area: 750 (69.68 sq.m.)Carpet area: 6...,2.0,2.0,0,not available,10.0,North,undefined,"['Dwaraka Expy, Tikampur Village', 'Sector 108...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN
1111,flat,"godrej 101, sector 79",sector 79,1.25,9038.0,1383.049347,Built Up area: 1383 (128.48 sq.m.),2.0,2.0,3,not available,1.0,East,undefined,"['Petrol Pump', 'Petrol Pump Indian Oil', 'Pet...","['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN

In [46]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [47]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)